### ISSUE TITLE
InvocationTargetException in CodeTogether 2023.1.1-01410

### ISSUE THREAD

**Issue by viraptor** [CodeTogether-Inc/CodeTogether-Live#410]
**Describe the bug**

Unknown source - I think it got triggered during/just after connection:

```
Internal error: java.lang.reflect.InvocationTargetException

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.genuitec.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$1(GenericEndpoint.java:67)
	at com.genuitec.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at com.genuitec.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at com.genuitec.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at com.genuitec.codetogether.services.LanguageServerService.handleRequest(LanguageServerService.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.genuitec.codetogether.comms.JsonRPCService.handle(JsonRPCService.java:133)
	at com.genuitec.codetogether.comms.BackendConnection.lambda$onMessage$3(BackendConnection.java:580)
	at com.genuitec.codetogether.comms.RpcWorkerPool$1.run(RpcWorkerPool.java:23)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.genuitec.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$1(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at com.genuitec.eclipse.lsp4j.services.TextDocumentService.documentHighlight(TextDocumentService.java:209)
	... 16 more
```

**To Reproduce**
Unknown.

**CodeTogether Host**
```
Build #RM-231.9011.41, built on May 17, 2023
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    net.sjrx.intellij.plugins.systemdunitfiles (223.230322.126)
    org.intellij.plugins.hcl (231.8109.91)
    org.toml.lang (231.8109.91)
    IdeaVIM (2.3.0)
    com.genuitec.codetogether (2023.1.1-01410)
```

**IDE Participant**
 - IDE: VSCode
 - IDE Version unknown
 - OS: macOS
 - OS Version: 13.4

**Comment by wgalanciak** [comment]
Thank you for reporting the issue. I was able to reproduce it using the following IDEs:
- host: IC-232.7754.73
- participant: VSCode 1.79.0
The issue should not affect functionality but we will schedule it to be fixed in the next update.
